Add AZ resources key vault and storage account
sukhdeepdev/azure-devops-sandbox pull request #16
Opened 2022-09-28 12:58 UTC by RajasekarVadivelu

2022-09-29 09:39 UTC, shantanuinamdar commented on sandbox/rajasekar/key-vault.tf
> +resource "azurerm_key_vault" "raj-key-vault" {
Suggestions from @sukhdeepsingh1 
resource naming, should be in snake_case & not to use type in the name

2022-09-29 09:40 UTC, shantanuinamdar commented on sandbox/rajasekar/main.tf
> +resource "azurerm_resource_group" "sandbox-rajasekar" {
same as above

2022-09-29 14:26 UTC, RajasekarVadivelu commented on sandbox/rajasekar/main.tf
> +resource "azurerm_resource_group" "sandbox-rajasekar" {
Replaced

2022-09-30 17:47 UTC, sukhdeepsingh1 requested changes

2022-09-30 17:47 UTC, sukhdeepsingh1 commented on sandbox/rajasekar/storage-account.tf
> +  account_replication_type = "GRS"
```suggestion
  account_replication_type = "LRS"
```

2022-10-01 06:42 UTC, RajasekarVadivelu commented on sandbox/rajasekar/storage-account.tf
> +  account_replication_type = "GRS"
changed to LRS

2022-10-01 09:46 UTC, sukhdeepsingh1 approved these changes

2022-10-04 14:14 UTC, merged